before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x16"
language: node_js
node_js:
  - 10
dist: trusty
script:
  - npm install
  - webdriver-manager update --gecko=false --versions.chrome=2.45 --versions.standalone=3.14.0
  - npm run update-webdriver
  - node conf-flake.js || exit 0
env:
  - suite=suite1
  - suite=suite2
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - graphicsmagick
      - ghostscript
  artifacts:
      paths:
        - ./allure-results
        - ./e2e-tests/artifacts
      target_paths: $TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER/results
notifications:
  slack: murcraft:4KfWGJMBr6kv3gR1iND1pVaO
  email:
    recipients:
      - ogulikpurse@gmail.com
    on_success: always
    on_failure: always
