language: node_js
node_js:
  - 10

os: windows
#dist: trusty

# install AVbin
before_install:
  - ls ~
  - choco install jdk8
  - export PATH=$PATH:"/c/Program Files/Java/jdk1.8.0_191/bin"
#  - chmod +x ./preinstall.sh
#  - ./preinstall.sh
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -L https://github.com/downloads/AVbin/AVbin/AVbin10.pkg -o AVbin10.pkg; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo installer -pkg AVbin10.pkg -target /; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1080x16; fi
#  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1080x16; fi
#  - export DISPLAY=:99.0
#  - Xvfb :99 -screen 0 1920x1080x16 > /dev/null 2>&1 &

before_script:
#  - chmod +x ./install-safari.sh ./run_tests.sh ./install.sh
#  - sh -e /etc/init.d/xvfb start &
#  - sleep 3
#  - bash ./install.sh
#  - if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then ( sudo Xvfb :99 -ac -screen 0 1920x1080x16; echo ok ) & fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sleep 3; fi
#  - if [[ "$TRAVIS_BUILD_STAGE_NAME" == "Chrome" ]]; then export browser=chrome; fi
#  - if [[ "$TRAVIS_BUILD_STAGE_NAME" == "Firefox" ]]; then export browser=firefox; fi
#  - if [[ "$TRAVIS_BUILD_STAGE_NAME" == "Safari" ]]; then export browser=safari; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export browser=ie; fi
  - ls
#  - if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then bash ./install-safari.sh; fi

stages:
#  - Chrome
#  - Firefox
#  - Safari
  - IE

script:
 - ls
# - system_profiler SPDisplaysDataType | grep Resolution
# - bash ./run_tests.sh || if [$? != 0]; then exit 0; fi
 - if [[ $browser == "ie" ]]; then npm run test-ie; fi

jobs:
 include:
# - stage: Chrome
#   env: suite=suite1
# - stage: Chrome
#   env: suite=suite2
# - stage: Chrome
#   env: suite=pdf
# - stage: Firefox
#   env: suite=suite1
# - stage: Firefox
#   env: suite=suite2
# - stage: Firefox
#   env: suite=pdf
# - stage: Safari
#   os: osx
#   osx_image: xcode10.2
#   env: suite=suite1
# - stage: Safari
#   os: osx
#   osx_image: xcode10.2
#   env: suite=suite2
# - stage: Safari
#   os: osx
#   osx_image: xcode10.2
#   env: suite=pdf
 - stage: IE
   env: suite=suite2
 - stage: IE
   env: suite=pdf

addons:
  firefox: "67.0"
  apt:
    packages:
    - google-chrome-stable
    - graphicsmagick
    - ghostscript
  homebrew:
    packages:
    - graphicsmagick
    - ghostscript
    - xvfb

  artifacts:
    s3_region: "us-west-2"
    paths:
    - ./allure-results
    - ./artifacts
    target_paths: $TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER/results

cache:
  directories:
    - node_modules

notifications:
  slack: murcraft:4KfWGJMBr6kv3gR1iND1pVaO
  email:
    recipients:
    - ogulikpurse@gmail.com
    on_success: always
    on_failure: always