sudo: required
dist: trusty

stages:
  - build docker image
  - test

branches:
 only:
  - master
  - dock

env:
  - suite=suite1
  - suite=suite2

jobs:
  include:
  - stage: build docker image
    env: suite=null
    script:
    - echo "$DOCKER_USERNAME" |docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker build -t travis-ci-build-e2e .
    - docker images
    - docker tag travis-ci-build-e2e $DOCKER_USERNAME/travis-ci-build-e2e
    - docker push $DOCKER_USERNAME/travis-ci-build-e2e
  - stage: test
    script:
    - mkdir allure-results
    - chmod chmod -R a=rwx $(pwd)
    - docker login -u perch1234 -p rtyfgh456
    - docker run -i -d --rm --net=host --privileged \
      -v /dev/shm:/dev/shm \
      -v $(pwd)/allure-results:/tests/allure-results \
      -e suite=$suite \
      -e maxinstances=2 \
      -e logLevel=$logLevel \
      --name e2e perch1234/e2e:latest
    - docker exec -it e2e bash -c 'xvfb-run -a node conf-flake.js'

addons:
  artifacts:
      paths:
        - ./allure-results
notifications:
  #slack: slack: murcraft:4KfWGJMBr6kv3gR1iND1pVaO
  email:
    recipients:
      - ogulikpurse@gmail.com
    on_success: always
    on_failure: always