language: node_js
node_js:
  - 10
dist: trusty
sudo: required
services:
  - xvfb
script:
  - npm test
env:
  - suite=suite1
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
notifications:
  slack: murcraft:4KfWGJMBr6kv3gR1iND1pVaO
  email:
    recipients:
      - ogulikpurse@gmail.com
    on_success: always
    on_failure: always
