language: node_js
node_js:
  - 10
dist: trusty

before_install:
- if [ "${TRAVIS_OS_NAME}" == "linux" ]; then "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x16"
- if [ "${TRAVIS_OS_NAME}" == "osx" ]; then "sudo Xvfb :99 -ac -screen 0 1024x768x8"

before_script:
- "export DISPLAY=:99.0"
- if [ "${TRAVIS_OS_NAME}" == "osx" ]; then "sudo Xvfb :99 -ac -screen 0 1024x768x8"
- if [ "${TRAVIS_OS_NAME}" == "linux" ]; then "sh -e /etc/init.d/xvfb start"
- sleep 3

env:
  - suite=suite1 browserName="chrome"
  - suite=suite1 browserName="firefox"
  - suite=suite2 browserName="chrome"
  - suite=suite2 browserName="firefox"

matrix:
  include:
  - os: linux
  - os: osx
  exclude:
  - os: osx
  env: browserName="firefox"

script:
- if [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew npm test; fi;
- if [ "${TRAVIS_OS_NAME}" == "linux" ]; then npm test; fi;

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
    - graphicsmagick
    - ghostscript
  homebrew:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
    - graphicsmagick
    - ghostscript
addons:
  firefox: "66.0"

  artifacts:
    paths:
    - ./allure-results
    - ./e2e-tests/artifacts
    target_paths: $TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER/results
notifications:
  slack: murcraft:4KfWGJMBr6kv3gR1iND1pVaO
  email:
    recipients:
    - ogulikpurse@gmail.com
    on_success: always
    on_failure: always