language: node_js
node_js:
  - 10
dist: trusty

before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3
before_install:
- ./install.sh

env:
- suite=suite1
- suite=suite2

matrix:
  include:
    - os: linux
      browserParam: "chrome"
    - os: osx
      browserParam: "chrome"


script:
- npm test || if [$? != 0]; then exit 0; fi

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
    - graphicsmagick
    - ghostscript
  artifacts:
    paths:
    - ./allure-results
    - ./e2e-tests/artifacts
    target_paths: $TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER/results
notifications:
  slack: murcraft:4KfWGJMBr6kv3gR1iND1pVaO
  email:
    recipients:
    - ogulikpurse@gmail.com
    on_success: always
    on_failure: always