language: node_js
node_js:
  - 10
dist: trusty

before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3

env:
  - suite=suite1
  - suite=suite2

matrix:
  include:
    - os: linux
      env: suite=suite1
      before_install:
      - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x16;
      before_script:
      - "export DISPLAY=:99.0"
      - "sh -e /etc/init.d/xvfb start"
      script:
      - npm i
      - ./node_modules/protractor/bin/webdriver-manager update
      - npm run update-webdriver --gecko=false --versions.chrome=2.45 --versions.standalone=3.4.0
      - node conf-flake.js -- browserName="chrome" || if [$? != 0]; then exit 0; fi;
    - os: osx
      before_install:
      - curl -L https://github.com/downloads/AVbin/AVbin/AVbin10.pkg -o AVbin10.pkg;
        sudo installer -pkg AVbin10.pkg -target /;
      before_script:
      - "export DISPLAY=:99.0"
      - sudo Xvfb :99 -ac -screen 0 1024x768x8; echo ok;
      script:
      - brew npm i
      - brew ./node_modules/protractor/bin/webdriver-manager update
      - brew npm run update-webdriver --gecko=false --versions.chrome=2.45 --versions.standalone=3.4.0
      - brew node conf-flake.js -- browserName="chrome"
    - os: linux
      before_install:
      - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x16;
      before_script:
      - "export DISPLAY=:99.0"
      - "sh -e /etc/init.d/xvfb start"
      script:
      - npm i
      - ./node_modules/protractor/bin/webdriver-manager update
      - npm run update-webdriver --versions.standalone=3.4.0
      - node conf-flake.js -- browserName="firefox"  || if [$? != 0]; then exit 0; fi;

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
    - graphicsmagick
    - ghostscript
  homebrew:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
    - graphicsmagick
    - ghostscript
addons:
  firefox: "66.0"

  artifacts:
    paths:
    - ./allure-results
    - ./e2e-tests/artifacts
    target_paths: $TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER/results
notifications:
  slack: murcraft:4KfWGJMBr6kv3gR1iND1pVaO
  email:
    recipients:
    - ogulikpurse@gmail.com
    on_success: always
    on_failure: always