language: node_js
node_js:
  - 10

os: linux
dist: trusty

# install AVbin
before_install:
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -L https://github.com/downloads/AVbin/AVbin/AVbin10.pkg -o AVbin10.pkg; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo installer -pkg AVbin10.pkg -target /; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1080x16; fi

before_script:
  - "export DISPLAY=:99.0"
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then ( sudo Xvfb :99 -ac -screen 0 1920x1080x16; echo ok ) & fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sleep 3; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo /Users/travis/build/murcraft/ProtractorGoogleTest/setSafariPath.scpt; fi

#matrix:
#  include:
#    - os: linux
#      dist: trusty
#      env: browser="chrome" suite=suite1
#    - os: linux
#      dist: trusty
#      env: browser="chrome" suite=suite2
#    - os: linux
#      dist: trusty
#      env: browser="chrome" suite=pdf
#    - os: linux
#      dist: trusty
#      env: browser="firefox" suite=suite1
#    - os: linux
#      dist: trusty
#      env: browser="firefox" suite=suite2
#    - os: linux
#      dist: trusty
#      env: browser="firefox" suite=pdf
#    - os: osx
#      env: browser="safari" suite=suite1
#    - os: osx
#      env: browser="safari" suite=suite2
#    - os: osx
#      env: browser="safari" suite=pdf
stages:
  - test
  - Firefox-tests
  - Safari-tests

env:
  - browser="chrome" suite=suite1
  - browser="chrome" suite=suite2
  - browser="chrome" suite=pdf


script:
# - if [[ $browser == "firefox" ]]; then npm run test-gecko; fi
 - if [[ $browser == "chrome" ]]; then npm run test-chrome; fi
# - if [[ $browser == "safari" ]]; then sudo safaridriver --enable; fi
# - if [[ $browser == "safari" ]]; then osascript /Users/travis/build/murcraft/ProtractorGoogleTest/setSafariPath.scpt; fi
# - if [[ $browser == "safari" ]]; then npm run test-safari; fi
 - npm test || if [$? != 0]; then exit 0; fi
#- npm run test-chrome || if [$? != 0]; then exit 0; fi

jobs:
 include:
 - stage: Firefox-tests
   env: browser="firefox" suite=suite1
   script: npm run test-gecko || if [$? != 0]; then exit 0; fi
 - stage: Firefox-tests
   env: browser="firefox" suite=suite2
   script: npm run test-gecko || if [$? != 0]; then exit 0; fi
 - stage: Firefox-tests
   env: browser="firefox" suite=pdf
   script: npm run test-gecko || if [$? != 0]; then exit 0; fi
 - stage: Safari-tests
   os: osx
   env: browser="safari" suite=suite1
   script:
   - sudo safaridriver --enable
   - npm run test-safari || if [$? != 0]; then exit 0; fi
 - stage: Safari-tests
   os: osx
   env: browser="safari" suite=suite2
   script:
   - sudo safaridriver --enable
   - npm run test-safari || if [$? != 0]; then exit 0; fi
 - stage: Safari-tests
   os: osx
   env: browser="safari" suite=pdf
   script:
   - sudo safaridriver --enable
   - npm run test-safari || if [$? != 0]; then exit 0; fi

addons:
  firefox: latest
  apt:
    chrome: stable
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
    - graphicsmagick
    - ghostscript
  homebrew:
    packages:
    - graphicsmagick
    - ghostscript

  artifacts:
    s3_region: "us-west-2"
    paths:
    - ./allure-results
    - ./artifacts
    target_paths: $TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER/results
notifications:
  slack: murcraft:4KfWGJMBr6kv3gR1iND1pVaO
  email:
    recipients:
    - ogulikpurse@gmail.com
    on_success: always
    on_failure: always