before_install:
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libappindicator1 fonts-liberation; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_77.0.3865.120-1_amd64.deb; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo dpkg -i google-chrome-stable_77.0.3865.120-1_amd64.deb; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1080x16; fi

before_script:
  - export CHROME_BIN=chromium-browser
  - export env=DEV
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

language: node_js
node_js:
- 10
dist: trusty
script:
- npm test || if [$? != 0]; then exit 0; fi

env:
- suite=suite1
- suite=suite2

addons:
  apt:
    packages:
    - graphicsmagick
    - ghostscript
  artifacts:
    s3_region: "us-west-2"
    paths:
    - ./allure-results
    - ./artifacts
    target_paths: $TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER/results
notifications:
  slack: murcraft:4KfWGJMBr6kv3gR1iND1pVaO
  email:
    recipients:
    - ogulikpurse@gmail.com
    on_success: always
    on_failure: always