before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3
before_install:
#- https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_75.0.3770.100_amd64.deb
- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x16"
language: node_js
node_js:
- 10
dist: trusty
script:
- npm test || if [$? != 0]; then exit 0; fi

env:
- suite=suite1
- suite=suite2

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
    - graphicsmagick
    - ghostscript
  artifacts:
    s3_region: "us-west-2"
    paths:
    - ./allure-results
    - ./artifacts
    target_paths: $TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER/results
notifications:
  slack: murcraft:4KfWGJMBr6kv3gR1iND1pVaO
  email:
    recipients:
    - ogulikpurse@gmail.com
    on_success: always
    on_failure: always