language: node_js
node_js:
  - 10
dist: trusty

# install AVbin
before_install:
  - if [ $TRAVIS_OS_NAME = osx ]; then
      curl -L https://github.com/downloads/AVbin/AVbin/AVbin10.pkg -o AVbin10.pkg;
      sudo installer -pkg AVbin10.pkg -target /;
    else
      /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render -noreset;
      dbus-launch pulseaudio --start;
    fi;
before_script:
  - "export DISPLAY=:99.0"
  - if [ $TRAVIS_OS_NAME = osx ]; then sudo Xvfb :99 -ac -screen 0 1024x768x8; else sh -e /etc/init.d/xvfb start; fi
  - sleep 3

env:
  - suite=suite1 browserName=chrome
  - suite=suite2 browserName=chrome
  - suite=suite1 browserName=firefox
  - suite=suite2 browserName=firefox

matrix:
  include:
  - os: linux
  - os: osx
  - os: linux
  exclude:
  - os: osx
  env: browserName=firefox

script:
- if [ $TRAVIS_OS_NAME = osx ]; then brew npm test; else npm test; fi

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
    - graphicsmagick
    - ghostscript
  homebrew:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
    - graphicsmagick
    - ghostscript
addons:
  firefox: "66.0"

  artifacts:
    paths:
    - ./allure-results
    - ./e2e-tests/artifacts
    target_paths: $TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER/results
notifications:
  slack: murcraft:4KfWGJMBr6kv3gR1iND1pVaO
  email:
    recipients:
    - ogulikpurse@gmail.com
    on_success: always
    on_failure: always