language: node_js
node_js:
  - 10

os: linux
dist: trusty

# install AVbin
before_install:
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -L https://github.com/downloads/AVbin/AVbin/AVbin10.pkg -o AVbin10.pkg; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo installer -pkg AVbin10.pkg -target /; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1080x16; fi

before_script:
  - "export DISPLAY=:99.0"
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then ( sudo Xvfb :99 -ac -screen 0 1920x1080x16; echo ok ) & fi
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then sudo safaridriver --enable; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sleep 3; fi
  - if [[ "$TRAVIS_BUILD_STAGE_NAME" == "chrome" ]]; then export browser=chrome; fi
  - if [[ "$TRAVIS_BUILD_STAGE_NAME" == "firefox" ]]; then export browser=firefox; fi
  - if [[ "$TRAVIS_BUILD_STAGE_NAME" == "safari" ]]; then export browser=safari; fi
  - chmod +x ./run_tests.sh
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo /Users/travis/build/murcraft/ProtractorGoogleTest/setSafariPath.scpt; fi

stages:
  - chrome
  - firefox
  - safari

script:
 - which safari
 - safari --version
 - bash ./run_tests.sh || if [$? != 0]; then exit 0; fi

jobs:
 include:
 - stage: chrome
   env: suite=suite1
 - stage: chrome
   env: suite=suite2
 - stage: chrome
   env: suite=pdf
 - stage: firefox
   env: suite=suite1
 - stage: firefox
   env: suite=suite2
 - stage: firefox
   env: suite=pdf
 - stage: safari
   os: osx
   env: suite=suite1
 - stage: safari
   os: osx
   env: suite=suite2
 - stage: safari
   os: osx
   env: suite=pdf

addons:
  firefox: "65.0"
  apt:
    chrome: stable
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
    - graphicsmagick
    - ghostscript
  homebrew:
    packages:
    - graphicsmagick
    - ghostscript

  artifacts:
    s3_region: "us-west-2"
    paths:
    - ./allure-results
    - ./artifacts
    target_paths: $TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER/results
notifications:
  slack: murcraft:4KfWGJMBr6kv3gR1iND1pVaO
  email:
    recipients:
    - ogulikpurse@gmail.com
    on_success: always
    on_failure: always