language: node_js
node_js:
  - 10

os: windows
#dist: trusty

# install AVbin
before_install:
  - echo $TRAVIS_OS_NAME
  - ls ~
  - dir 'C:\Program Files\internet explorer\.'
  - dir 'C:\ProgramData'
#  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install ie11; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install jdk8; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export JAVA_HOME="C:\jdk8"; fi
#  - href="https://go.microsoft.com/fwlink/?LinkId=324629"
  - export PATH=${JAVA_HOME}/bin:${PATH}
  - export PATH=$PATH:"/c/Program Files/Java/jdk1.8.0_221/bin"
  - echo $PATH
  - java -version
  - powershell dism /online /get-features
#  - chmod +x ./preinstall.sh
#  - ./preinstall.sh
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -L https://github.com/downloads/AVbin/AVbin/AVbin10.pkg -o AVbin10.pkg; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo installer -pkg AVbin10.pkg -target /; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1080x16; fi
#  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1080x16; fi
#  - export DISPLAY=:99.0
#  - Xvfb :99 -screen 0 1920x1080x16 > /dev/null 2>&1 &

before_script:
#  - chmod +x ./install-safari.sh ./run_tests.sh ./install.sh
#  - sh -e /etc/init.d/xvfb start &
#  - sleep 3
#  - bash ./install.sh
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then REG ADD 'HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3\2500'; fi
#  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then REG ADD 'HHKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BFCACHE'; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then REG ADD 'HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BFCACHE'; fi
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then ( sudo Xvfb :99 -ac -screen 0 1920x1080x16; echo ok ) & fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sleep 3; fi
#  - if [[ "$TRAVIS_BUILD_STAGE_NAME" == "Chrome" ]]; then export browser=chrome; fi
#  - if [[ "$TRAVIS_BUILD_STAGE_NAME" == "Firefox" ]]; then export browser=firefox; fi
#  - if [[ "$TRAVIS_BUILD_STAGE_NAME" == "Safari" ]]; then export browser=safari; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export browser=ie; fi
#  - if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then bash ./install-safari.sh; fi

stages:
#  - Chrome
#  - Firefox
#  - Safari
  - IE

script:
# - system_profiler SPDisplaysDataType | grep Resolution
 - bash ./run_tests.sh || if [$? != 0]; then exit 0; fi
# - npm run test-ie
#|| if [$? != 0]; then exit 0; fi

jobs:
 include:
 - stage: IE
   env: suite=suite1
 # - stage: Chrome
#   env: suite=suite2
# - stage: Chrome
#   env: suite=pdf
# - stage: Firefox
#   env: suite=suite1
# - stage: Firefox
#   env: suite=suite2
# - stage: Firefox
#   env: suite=pdf
# - stage: Safari
#   os: osx
#   osx_image: xcode10.2
#   env: suite=suite1
# - stage: Safari
#   os: osx
#   osx_image: xcode10.2
#   env: suite=suite2
# - stage: Safari
#   os: osx
#   osx_image: xcode10.2
#   env: suite=pdf
 - stage: IE
   env: suite=suite2
 - stage: IE
   env: suite=pdf

addons:
#  firefox: "67.0"
  apt:
    packages:
    - google-chrome-stable
    - graphicsmagick
    - ghostscript
  homebrew:
    packages:
    - graphicsmagick
    - ghostscript
    - xvfb

#  artifacts:
#    s3_region: "us-west-2"
#    paths:
#    - ./allure-results
#    - ./artifacts
#    target_paths: $TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER/results

notifications:
  slack: murcraft:4KfWGJMBr6kv3gR1iND1pVaO
  email:
    recipients:
    - ogulikpurse@gmail.com
    on_success: always
    on_failure: always