language: node_js
node_js:
  - 10

# install AVbin
before_install:
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -L https://github.com/downloads/AVbin/AVbin/AVbin10.pkg -o AVbin10.pkg; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo installer -pkg AVbin10.pkg -target /; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1080x16; fi

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sleep 3; fi

env:
 - suite=suite1 browser="safari"
 - suite=suite2 browser="safari"
 - suite=pdf browser="safari"
 - suite=suite1 browser="firefox"
 - suite=suite2 browser="firefox"
 - suite=pdf browser="firefox"
 - suite=suite1 browser="chrome"
 - suite=suite2 browser="chrome"
 - suite=pdf browser="chrome"

matrix:
  exclude:
    - os: osx
      env: suite=suite1 browser="chrome"
    - os: osx
      env: suite=suite2 browser="chrome"
    - os: osx
      env: suite=pdf browser="chrome"
    - os: osx
      env: suite=suite1 browser="firefox"
    - os: osx
      env: suite=suite2 browser="firefox"
    - os: osx
      env: suite=pdf browser="firefox"
    - os: linux
      env: suite=suite1 browser="safari"
    - os: linux
      env: suite=suite2 browser="safari"
    - os: linux
      env: suite=pdf browser="safari"

script:
 - if [[ $browser == "firefox" ]]; then npm run test-gecko; fi
 - if [[ $browser == "chrome" ]]; then npm run test-chrome; fi
 - if [[ $browser == "safari" ]]; then sudo safaridriver --enable; fi
 - if [[ $browser == "safari" ]]; then npm run test-safari; fi
 - npm test || if [$? != 0]; then exit 0; fi

addons:
  chrome: stable
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - graphicsmagick
    - ghostscript
    homebrew:
      sources:
      - google-chrome
      packages:
      - graphicsmagick
      - ghostscript

  artifacts:
    s3_region: "us-west-2"
    paths:
    - ./allure-results
    - ./artifacts
    target_paths: $TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER/results
notifications:
  slack: murcraft:4KfWGJMBr6kv3gR1iND1pVaO
  email:
    recipients:
    - ogulikpurse@gmail.com
    on_success: always
    on_failure: always