before_script:
  - "export DISPLAY=:99.0"
  - "sh /etc/init.d/xvfb start"
  - sleep 3
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x16 --exit-zero"
language: node_js
node_js:
  - 8
dist: trusty
env: suite=suite1
after script:
  - "sh exit 0"
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - graphicsmagick
      - ghostscript
  artifacts:
      paths:
        - ./allure-results
        - ./e2e-tests/artifacts
      target_paths: $TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER/results
notifications:
  slack: murcraft:4KfWGJMBr6kv3gR1iND1pVaO
  email:
    recipients:
      - ogulikpurse@gmail.com
    on_success: always
    on_failure: always
